name: CI

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - run: yarn cache dir
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Frontend Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run Tests
        run: |
          ls
          yarn test
