name: Publish to npm
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: ableco
      - run: |
          npm install
          npm publish --@ableco:registry=https://registry.npmjs.org/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
